
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RISHABH
 */
public class Cancel extends javax.swing.JFrame {
String id;
    /**
     * Creates new form Cancel
     */
    public Cancel() {
        initComponents();
    }
 public Cancel(String uid) {
        initComponents();
        id=uid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        notf = new javax.swing.JTextField();
        fidtf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Flight Id");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 160, 120, 30);

        notf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notf.setForeground(new java.awt.Color(153, 0, 153));
        notf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(notf);
        notf.setBounds(220, 220, 160, 30);

        fidtf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fidtf.setForeground(new java.awt.Color(153, 0, 153));
        fidtf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(fidtf);
        fidtf.setBounds(220, 160, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("CANCEL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 60, 230, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("No. of Tickets");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 220, 120, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 330, 120, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dialog_cancel.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 290, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/air_tickets.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 230, 160, 130);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previous.png"))); // NOI18N
        jLabel8.setToolTipText("CLICK ON IT TO GO BACK TO HOME");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 10, 80, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a31.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");  
        String fid=fidtf.getText();
        int ticket=Integer.parseInt(notf.getText());
PreparedStatement stmt=con.prepareStatement("select tickets from booking where flight_id=? and user_id=?");
stmt.setString(1,fid);
stmt.setString(2,id);
ResultSet rs=stmt.executeQuery();
rs.next();
int t=rs.getInt(1);
System.out.println(""+t);
ticket=t-ticket;
if(ticket < 0)
JOptionPane.showMessageDialog(null,"Can not cancel bcz you had booked less tickets than the tickets you wants to cancel");
else
{
    if(ticket==0)
    {
       PreparedStatement stmt2=con.prepareStatement("delete from booking where flight_id=? and user_id=?");
       stmt2.setString(1,fid);
stmt2.setString(2,id);
stmt2.executeUpdate();
    }
    else
    {
       PreparedStatement stmt3=con.prepareStatement("update booking set tickets=? where flight_id=? and user_id=?");
       stmt3.setInt(1,ticket);
       stmt3.setString(2,fid);
stmt3.setString(3,id);
stmt3.executeUpdate(); 
    }
    JOptionPane.showMessageDialog(null,"Successfully canceled you will get back your refund within 24 hours");
    new Booked(id).setVisible(true);
    this.setVisible(false);
}// TODO add your handling code here:
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Cancel.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Cancel.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        new Menu().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fidtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField notf;
    // End of variables declaration//GEN-END:variables
}
