
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RISHABH
 */
import java.math.*;
import javax.swing.JOptionPane;
public class Payment extends javax.swing.JFrame {
static String id;
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }
     public Payment(String a) {
        initComponents();
        id=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cvvtf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        notf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        amttf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("PAYMENT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 30, 230, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Amount");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 330, 120, 40);

        cvvtf.setForeground(new java.awt.Color(0, 102, 51));
        cvvtf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cvvtf);
        cvvtf.setBounds(200, 270, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Debit Card No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 110, 120, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Month");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 190, 60, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Year");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(310, 190, 60, 17);

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cb1.setSelectedItem(null);
        getContentPane().add(cb1);
        cb1.setBounds(200, 210, 70, 30);

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35" }));
        cb2.setSelectedItem(null);
        getContentPane().add(cb2);
        cb2.setBounds(290, 210, 70, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Expiry Date");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 200, 120, 40);

        notf.setForeground(new java.awt.Color(0, 102, 0));
        notf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        notf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notfActionPerformed(evt);
            }
        });
        getContentPane().add(notf);
        notf.setBounds(200, 120, 170, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("CVV");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 270, 120, 40);

        amttf.setForeground(new java.awt.Color(0, 102, 51));
        amttf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(amttf);
        amttf.setBounds(200, 330, 170, 30);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 255));
        jButton1.setText("PAY NOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 410, 120, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/credit_card.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 30, 160, 100);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previous.png"))); // NOI18N
        jLabel11.setToolTipText("");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 0, 80, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\RISHABH\\Pictures\\a8.jpg")); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 570, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
        BigInteger c_no=new BigInteger(notf.getText());
        String card_no=c_no.toString();
       // int card_no=Integer.parseInt(notf.getText());
        String month=(String)cb1.getSelectedItem();
        String year=(String)cb2.getSelectedItem();
        int m=Integer.parseInt(month);
        int y=Integer.parseInt(year);
        int amount=Integer.parseInt(amttf.getText());
        int cvv=Integer.parseInt(cvvtf.getText());

  PreparedStatement st=con.prepareStatement("insert into payment values(?,?,?,?,?,?)");
st.setString(1,id);
st.setString(2,card_no);
st.setInt(3,m);
st.setInt(4,y);
st.setInt(5,cvv);
st.setInt(6,amount);
st.executeUpdate();
PreparedStatement s=con.prepareStatement("update booking set payment_done=? where user_id=? and fare=?");
s.setString(1, "Yes");
s.setString(2,id);
s.setInt(3,amount);
s.executeUpdate();
JOptionPane.showMessageDialog(null,"Your payment has been successfully done");
new Menu().setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void notfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notfActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new Booked().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amttf;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JTextField cvvtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField notf;
    // End of variables declaration//GEN-END:variables
}
