
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RISHABH
 */
public class Search_flight extends javax.swing.JFrame {
static String id;
    /**
     * Creates new form Search_flight
     */
    public Search_flight() {
        initComponents();
    }
    public Search_flight(String a) {
        initComponents();
        id=a;
    }
Book b=new Book(id);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("SEARCH FLIGHT FORM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 20, 300, 40);

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DELHI", "MUMBAI", "BANGALORE", "LUCKNOW", "GOA" }));
        cb1.setSelectedItem(null
        );
        getContentPane().add(cb1);
        cb1.setBounds(230, 150, 120, 30);

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GOA", "BANGALORE", "MUMBAI", "DELHI", "LUCKNOW" }));
        cb2.setSelectedItem(null);
        getContentPane().add(cb2);
        cb2.setBounds(550, 150, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("CLICK ON RESPECTIVE ROW TO BOOK THAT FLIGHT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 440, 390, 20);

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("SEARCH");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 230, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("SOURCE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 150, 80, 20);

        t1.setBackground(new java.awt.Color(51, 255, 255));
        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FLIGHT NAME", "FLIGHT ID", "SOURCE", "DESTINATION", "ARRIVAL", "STOPS", "DURATION", "FARE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 770, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/find.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(590, 10, 210, 120);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("DESTINATION");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 150, 120, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previous.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 20, 80, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\RISHABH\\Pictures\\a15.jpg")); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(780, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 850, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
            Statement stmt=con.createStatement();
              DefaultTableModel model=(DefaultTableModel)t1.getModel();
           model.setRowCount(0);
             String source=(String)cb1.getSelectedItem();
             String destination=(String)cb2.getSelectedItem();
             if(source.equals(destination))
                 JOptionPane.showMessageDialog(null,"Source and Destination can not be same.");
            PreparedStatement st=con.prepareStatement("select * from flight_details where source=? and destination=?");
           
            st.setString(1,source );
            st.setString(2,destination);
            ResultSet rs = st.executeQuery();
         
            while(rs.next())
            {
               String a=rs.getString(1);
                String b=rs.getString(2);
                 String c=rs.getString(3);
                  String d=rs.getString(4);
                   String e=rs.getString(5);
                    String f=rs.getString(6);
                     String g=rs.getString(7);
                      String h=rs.getString(8);
                Object[] row={a,b,c,d,e,f,g,h};
                model.addRow(row);
            }
            
            con.close();    // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Search_flight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Search_flight.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
int index=t1.getSelectedRow();
DefaultTableModel model=(DefaultTableModel)t1.getModel();
String fid=model.getValueAt(index, 1).toString();
String source=model.getValueAt(index, 2).toString();
String destination=model.getValueAt(index, 3).toString();
b.setVisible(true);
//b.pack();
b.uidtf.setText(id);
b.fidtf.setText(fid);
b.sourcetf.setText(source);
b.destf.setText(destination);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_t1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new Menu().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_flight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t1;
    // End of variables declaration//GEN-END:variables
}
